mapping = {
    ### income statement variable ###
    'date': 'date',
    'currency': 'reportedCurrency',
    'revenue': 'revenue',
    'grossProfit': 'grossProfit',
    'margin': 'grossProfit',
    'R&DExpense': 'researchAndDevelopmentExpenses',
    'AdminExpense': 'generalAndAdministrativeExpenses',
    'MarketingExpense': 'sellingAndMarketingExpenses',
    'Admin&MarketingExpense': 'sellingGeneralAndAdministrativeExpenses',
    'otherExpense': 'otherExpenses',
    'operatingExpense': 'operatingExpenses',
    'cost&expense': 'costAndExpenses',
    'interstIncome': 'interestIncome',
    'interstExpense': 'interestExpense',
    'D&A': 'depreciationAndAmortization',
    'ebitda': 'ebitda',
    'ebitdaRatio': 'ebitdaratio',
    'operatingIncome': 'operatingIncome',
    'operatingIncomeRatio': 'operatingIncomeRatio',
    'totalOtherIncomeExpensesNet': 'totalOtherIncomeExpensesNet',
    'incomeBeforeTax': 'incomeBeforeTax',
    'incomeBeforeTaxRatio': 'incomeBeforeTaxRatio',
    'incomeTaxExpense': 'incomeTaxExpense',
    'netIncome': 'netIncome',
    'netIncomeRatio': 'netIncomeRatio',
    'eps': 'eps',
    'epsdiluted': 'epsdiluted',
    'weightedAverageShsOut': 'weightedAverageShsOut',
    'weightedAverageShsOutDil': 'weightedAverageShsOutDil',
    ### income statement variable ###
    ### cashflow statement variable ###
    'deferIncTax': 'deferredIncomeTax',
    'stockComp': 'stockBasedCompensation',
    'changeWC': 'changeInWorkingCapital',
    'AR': 'accountsReceivables',
    'inv': 'inventory',
    'AP': 'accountsPayables',
    'otherWC': 'otherWorkingCapital',
    'otherNonCash': 'otherNonCashItems',
    'netCashOpera': 'netCashProvidedByOperatingActivities',
    'investPP&E': 'investmentsInPropertyPlantAndEquipment',
    'acquisitionNet': 'acquisitionsNet',
    'purchaseInvest': 'purchasesOfInvestments',
    'salesMaturities': 'salesMaturitiesOfInvestments',
    'otherInvest': 'otherInvestingActivites',
    'netCashInvest': 'netCashUsedForInvestingActivites',
    'debtRepay': 'debtRepayment',
    'commonStockIss': 'commonStockIssued',
    'commonStockRep': 'commonStockRepurchased',
    'dividend': 'dividendsPaid',
    'otherFinance': 'otherFinancingActivites',
    'netCashFinance': 'netCashUsedProvidedByFinancingActivities',
    'effectFX': 'effectOfForexChangesOnCash',
    'netChangeCash': 'netChangeInCash',
    'cashEnd': 'cashAtEndOfPeriod',
    'cashBegin': 'cashAtBeginningOfPeriod',
    'operaCF': 'operatingCashFlow',
    'capitalExp': 'capitalExpenditure',
    'freeCF': 'freeCashFlow',
    ### cashflow statement variable ###
    ### balancesheet statement variable ###
    'cash&equival': 'cashAndCashEquivalents',
    'shortTermInvest': 'shortTermInvestments',
    'cash&short': 'cashAndShortTermInvestments',
    'netReceivables': 'netReceivables',
    ## 'inventory', ## In cashflow statement, there is inv map
    'otherCurAsset': 'otherCurrentAssets',
    'totalCurAsset': 'totalCurrentAssets',
    'PP&E': 'propertyPlantEquipmentNet',
    'goodwill': 'goodwill',
    'intangibleAsset': 'intangibleAssets',
    'goodwill&intangible': 'goodwillAndIntangibleAssets',
    'longTermInvest': 'longTermInvestments',
    'taxAsset': 'taxAssets',
    'otherNonCurAsset': 'otherNonCurrentAssets',
    'totalNonCurAsset': 'totalNonCurrentAssets',
    'otherAsset': 'otherAssets',
    'totalAsset': 'totalAssets',
    'APs': 'accountPayables',
    'shortTermDebt': 'shortTermDebt',
    'taxPayable': 'taxPayables',
    'DR': 'deferredRevenue',
    'otherCurLiability': 'otherCurrentLiabilities',
    'totalCurLiability': 'totalCurrentLiabilities',
    'longTermDebt': 'longTermDebt',
    'DRNonCur': 'deferredRevenueNonCurrent',
    'deferTaxLiabilityNonCur': 'deferredTaxLiabilitiesNonCurrent',
    'otherNonCurLiability': 'otherNonCurrentLiabilities',
    'totalNonCurLiability': 'totalNonCurrentLiabilities',
    'otherLiability': 'otherLiabilities',
    'capitalLease': 'capitalLeaseObligations',
    'totalLiability': 'totalLiabilities',
    'preStock': 'preferredStock', 
    'comStock': 'commonStock', 
    'RE': 'retainedEarnings',
    'otherComprehensivePL': 'accumulatedOtherComprehensiveIncomeLoss',
    'otherTotalEquity': 'othertotalStockholdersEquity',
    'totalStockEquity': 'totalStockholdersEquity',
    'totalEquity': 'totalEquity',
    'totalL&StockE': 'totalLiabilitiesAndStockholdersEquity',
    'minorInt': 'minorityInterest',
    'totalL&E': 'totalLiabilitiesAndTotalEquity',
    'totalInvest': 'totalInvestments',
    'totalDebt': 'totalDebt',
    'netDebt': 'netDebt'
    ### balancesheet statement variable ###
}

valuationMapping = {
    ### Advanced DCF ###
    'year': 'year',
    'price': "price",
    'beta': 'beta',
    'finalTaxRate': 'finalTaxRate',
    'totalDebt': "totalDebt",
    'totalEquity': "totalEquity",
	'totalCapital': "totalCapital",
	'dilutedShare': "dilutedSharesOutstanding",
	'debtWeight': "debtWeighting",
	'equityWeight': "equityWeighting",
	'period': "period",
	'revenue': "revenue",
	'ebitda': "ebitda",
	'operatingCF': "operatingCashFlow",
	'ebit': "ebit",
	'avgWeightShare': "weightedAverageShsOutDil",
	'netDebt': "netDebt",
	'inventory': "inventories",
	'receivables': "receivables",
	'payable': "payable",
	'inventoryDiff': "inventoriesChange",
	'receivableDiff': "receivablesChange",
	'payableDiff': "payableChange",
	'capExp': "capitalExpenditure",
	'priorRevenue': "previousRevenue",
	'revenuePercent': "revenuePercentage",
	'taxRate': "taxRate",
	'ebitdaPercent': "ebitdaPercentage",
	'receivablePercent': "receivablesPercentage",
	'inventoryPercent': "inventoriesPercentage",
	'payablePercent': "payablePercentage",
	'ebitPercent': "ebitPercentage",
	'capExpPercent': "capitalExpenditurePercentage",
	'operatingCFPercent': "operatingCashFlowPercentage",
	'postTaxCostDebt': "afterTaxCostOfDebt",
	'marketRiskPremium': "marketRiskPremium",
	'growthRateLT': "longTermGrowthRate",
	'costOfEquity': "costOfEquity",
	'WACC': "wacc",
	'cashTaxRate': "taxRateCash",
	'ebiat': "ebiat",
	'ufcf': "ufcf",
	'riskFreeRate': "riskFreeRate",
	'sumPvUfcf': "sumPvUfcf",
	'terminalValue': "terminalValue",
	'presentTerminalValue': "presentTerminalValue",
	'EV': "enterpriseValue",
	'equityValue': "equityValue",
	'equityValuePerShare': "equityValuePerShare",
	'freeCashFlowT1': "freeCashFlowT1",
	'costOfDebt': "costofDebt",
	'dep': "depreciation",
	'totalCash': "totalCash",
	'depPercent': "depreciationPercentage",
	'totalCashPercent': "totalCashPercentage"
    ### Advanced DCF ###
    ### Levered DCF ###
    ### Levered DCF ###
}

ratioMapping = {
    ### Key Metric Quarterly ###
    "symbol": "symbol",
    "date": "date",
    'year': "calendarYear",
    'period': "period",
    'revShare': "revenuePerShare",
    'NIShare': "netIncomePerShare",
    'OperaCFShare': "operatingCashFlowPerShare",
    'FCFShare': "freeCashFlowPerShare",
    'cashShare': "cashPerShare",
    'BVShare': "bookValuePerShare",
    'tangibleBVShare': "tangibleBookValuePerShare",
    'SHEquityShare': "shareholdersEquityPerShare",
    'interestDebtShare': "interestDebtPerShare",
    'MV': "marketCap",
    'EV': "enterpriseValue",
    'PE': "peRatio",
    'PS': "priceToSalesRatio",
    'PCF': "pocfratio",
    'PFCF': "pfcfRatio",
    'PB': "pbRatio",
    'PTB': "ptbRatio",
    'EVtoSales': "evToSales",
    'EVtoEBITDA': "enterpriseValueOverEBITDA",
    'EVtoOperaCF': "evToOperatingCashFlow",
    'EVtoFCF': "evToFreeCashFlow",
    'EarningYield': "earningsYield",
    'FCFYield': "freeCashFlowYield",
    'debtEquity': "debtToEquity",
    'debtAsset': "debtToAssets",
    'netDebtEBITDA': "netDebtToEBITDA",
    'CA': "currentRatio",
    'IntCoverage': "interestCoverage",
    'IncQuality': "incomeQuality",
    'dividendYield': "dividendYield",
    'payoutRatio': "payoutRatio",
    'AdmintoRevenue': "salesGeneralAndAdministrativeToRevenue",
    'research&developtoRevenue': "researchAndDdevelopementToRevenue",
    'intangibletoAsset': "intangiblesToTotalAssets",
    'CapExtoOperaCF': "capexToOperatingCashFlow",
    'CapExtoRevenue': "capexToRevenue",
    'CapExtoDepre': "capexToDepreciation",
    'stockComptoRevenue': "stockBasedCompensationToRevenue",
    'grahamNumber': "grahamNumber",
    'ROIC': "roic",
    'ROTangibleAsset': "returnOnTangibleAssets",
    'grahamNetNet': "grahamNetNet",
    'WC': "workingCapital",
    'tangibleAsset': "tangibleAssetValue",
    'netCurrentAsset': "netCurrentAssetValue",
    'investedCapital': "investedCapital",
    'avgReceivables': "averageReceivables",
    'avgPayables': "averagePayables",
    'avgInv': "averageInventory",
    'daysSalesOutstanding': "daysSalesOutstanding",
    'daysPayablesOutstanding': "daysPayablesOutstanding",
    'daysInv': "daysOfInventoryOnHand",
    'receivablesTurnover': "receivablesTurnover",
    'payablesTurnover': "payablesTurnover",
    'InvTurnover': "inventoryTurnover",
    'ROE': "roe",
    'CapExShare': "capexPerShare"
    ### Key Metric Quarterly ###
}

dividendMapping = {
    "date": "date",
    "label": "label",
    "divAdj": "adjDividend",
    "div": "dividend",
    "recordDate": "recordDate",
    "paymentDate": "paymentDate",
    "declarationDate": "declarationDate"
}

ratioTTMMapping = {
    ### Key Metric TTM ###
    
    ### Key Metric TTM ###
}

CFGrowthMapping = {

}

IncGrowthMapping = {

}

BSGrowthMapping = {

}

FinancialGrowthMapping = {

}